### ISSUE TITLE
feat: avoiding automatic custom role creation

### ISSUE THREAD

**Issue by vjofusha** [lacework/terraform-gcp-agentless-scanning#32]
Description:

When the global input variable is set to "true," everything functions smoothly as all the necessary resources are automatically
created. However, in our scenario, we cannot permit the Terraform module to generate custom roles with highly specific
permissions, such as the [ability to create and delete resources at the project level](https://github.com/lacework/terraform-gcp-agentless-scanning/blob/main/custom_roles.tf). 

To prevent the module from creating the custom role on our behalf, we must set the input global to `false`. Because of this, nothing is created on the module side, as all resources are generated based on the global input set to `true`. I am trying to understand the idea behind this and if there is another way to get around this problem. 

1. Is it possible to support organization-level custom roles that are not based on the variable "global". Introducing a more flexible approach that does not solely rely on this variable would be beneficial. Ideally, we'd like to be able to input a service account assigned to our custom role, allowing for a more customized setup without having to recreate the entire module ourselves if "global" is set to false.

2. I would also appreciate clarifying why all those permissions are needed for agentless scanning.

**Comment by qianxuweiren** [comment]
Hello @vjofusha , to clarify, there are two types of resources that agentless scanning creates--global and regional. `global` indicates that resources are created only once and shared among all regions, whereas `regional` indicates that resources are created once for each region and only used by that region. In deployment, global resources are deployed first (`global == true`), and then they are passed down to regional resources (`global == false`) via `global_module_reference` so regional deployment knows how to access those global resources.

Permissions defined in those roles are useful for creating necessary resources for scanning (e.g. creating snapshots). They are scoped to the GCP project that gets created by Terraform so they won't affect other projects in production.
